name: OPML Release

on:
  workflow_dispatch:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v2
      with:
        node-version: 14.x
    - run: npm ci
    - name: Build
      run: npm run build
    - name: Create artifacts
      uses: actions/upload-artifact@v2
      with:
        path: |
          README.md
          feeds.ompl
          feeds.*.opml
    - name: Get current date
      id: date
      run: echo "::set-output name=date::$(date +'%Y.%m.%d')"
    - name: Release
      uses: softprops/action-gh-release@v1
      with:
        name: 'Release at ${{ steps.date.outputs.date }}'
        tag_name: 'v${{ steps.date.outputs.date }}'
        files: |
          feeds.opml
          feeds.*.opml
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    - uses: EndBug/add-and-commit@v7
      with:
        add: README.md
        message: 'Update at ${{ steps.date.outputs.date }}'
